name: "Python CI"
on:
  push: 
    branches: [ main, ci-test*]
  pull_request:
    branches: [ main, stable , ci-test*]      
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      min-python-version: "3.9"
    steps:

      - name: Copy Repository Contents
        uses: actions/checkout@main   
   
      - name: Install Conda environment with Micromamba and Run Tests
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-environment.yml
          environment-name: harrypy
          cache-environment: true
          cache-downloads: true
          
      - run: |
          micromamba activate harrypy
          pytest 

  lint:
    runs-on: ubuntu-latest
    env:
      min-python-version: "3.9"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python ${{ env.min-python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.min-python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Check black formatting
        run: black . --check
        if: success() || failure()

      - name: Check isort formatting
        run: isort . --check
        if: success() || failure()

      - name: Check mypy formatting
        run: mypy
        if: success() || failure()

