name: "Unit Tests - Mamba"
on:
  pull_request:      
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Copy Repository Contents
        uses: actions/checkout@main   
   
      - name: Install Conda environment with Micromamba and Run Tests
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-environment.yml
          environment-name: harrypy
          cache-environment: true
          cache-downloads: true
          
      - run: |
          micromamba activate harrypy
          pytest 
